name: Automation

on:
  push:
    branches: ["main"]
  schedule:
    # at 7:00, 7:30, ..., 22:00 (no DST = UTC+2)
    - cron: '0,30 5-20 * 4-10 *'
    # same thing during DST (UTC+1)
    - cron: '0,30 6-21 * 1-3,11-12 *'
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Cache data
      uses: actions/cache@v4
      with:
        path: |
          gmail_messages.json
          gmx_messages.json
        key: ${{ github.sha }}

    - name: Check Gmail emails
      run: python check_gmail_emails.py

    - name: Check GMX emails
      run: python check_gmx_emails.py
