name: Automation

on:
  push:
    branches: ["main"]
  schedule:
    # At 7:00, 7:30, ..., 22:00 (no DST = UTC+2)
    - cron: '0,30 5-20 * 4-10 *'
    # Same thing during DST (UTC+1)
    - cron: '0,30 6-21 * 1-3,11-12 *'
  workflow_dispatch:
    inputs:
      restoreCache:
        description: Restore cache
        required: false
        type: boolean

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Restore the cached data
      uses: actions/cache/restore@v4
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || inputs.restoreCollection }}
      with:
        path: |
          message_*
          todoist_status_*.json
        key: cache-${{ hashFiles('message_*', 'todoist_status_*.json') }}
        restore-keys: cache-

    - name: Check emails
      run: python main.py
      env:
        GMX_USER: ${{ secrets.GMX_USER }}
        GMX_PASSWORD: ${{ secrets.GMX_PASSWORD }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        TODOIST_CLIENT_ID: ${{ secrets.TODOIST_CLIENT_ID }}
        TODOIST_CLIENT_SECRET: ${{ secrets.TODOIST_CLIENT_SECRET }}
        TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}

    - name: Cache data
      uses: actions/cache/save@v4
      with:
        path: |
          message_*
          todoist_status_*.json
        key: cache-${{ hashFiles('message_*', 'todoist_status_*.json') }}
